### ISSUE TITLE
可否將此兩個方案配方化？

### ISSUE THREAD

**Issue by laubonghaudoi** [einverne/rime-hangul#1]
目前本倉庫內兩個方案未配方化，無法一鍵安裝下載。配方化的方法很簡單，只需要把全部`yaml`文件放到頂層目錄即可。

**Comment by einverne** [comment]
我研究一下 :)

**Comment by einverne** [comment]
@laubonghaudoi 幫忙review [一下](https://github.com/einverne/rime-hangul/pull/2) 這樣是否就可以了。

**Comment by laubonghaudoi** [comment]
是的就是這樣，非常感謝，這樣在plum裏只需要命令行輸入`einverne/rime-hangul`再回車就能一鍵安裝這兩個方案

**Comment by einverne** [comment]
我一直用純手工的方式管理，学习了。
