### ISSUE TITLE
不好意思，想請教안녕하세요要怎麼輸入？

### ISSUE THREAD

**Issue by laichiaheng** [einverne/rime-hangul#4]
不好意思，我沒有學過韓語，不過想要嘗試看看輸入韓語的感覺，請問안녕하세요這句話要怎麼輸入呢？
請問這個和洋蔥有關的話，是否用洋蔥他的 RIME mix-in 輸入法使用同樣的方法輸入呢？
因為查了網路上韓文輸入的方式，好像按鍵位置都不太一樣。

**Comment by einverne** [comment]
你好，不知道你說的是哪一個方案，這個倉庫包含了好几套輸入方案。

如果是 rime-hangyl 這個方案，在 README 中有演示，输入

an nieng ha sei yo 

因为这是一套根据音码转写的方案，和大陆的拼音特别类似，所以不用记忆韩语 2set 按键的分布。

而如果你要使用韩国标准的键盘布局，可以使用 2set 方案。
